AWSTemplateFormatVersion: '2010-09-09'
Description: Auto Scaling and Load Balancer for E-commerce Platform

Parameters:
  VPCId:
    Type: String
    Description: The VPC ID where the resources will be deployed.
    Default: !ImportValue VPCId

  PublicSubnetId1:
    Type: String
    Description: The public subnet ID for EC2 instances.
    Default: !ImportValue PublicSubnetId1
  
  PublicSubnetId2:
    Type: String
    Description: The public subnet ID for EC2 instances.
    Default: !ImportValue PublicSubnetId2

  KeyName:
    Description: Name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro

  RDSfromEC2SecurityGroupId:
    Description: RDS to EC2 Security Group
    Type: AWS::EC2::SecurityGroup
    Default: !ImportValue RDSfromEC2SecurityGroupId

  EC2toRDSSecurityGroupId:
    Description: EC2 to RDS Security Group
    Type: AWS::EC2::SecurityGroup
    Default: !ImportValue EC2toRDSSecurityGroupId
  
  AMIId:
    Description: Base Ubuntu Image for Instances in EC2 instances
    Type: String
    Default: "ami-xxxxxxxxxxxxx"

Resources:

  # Security Group for Load Balancer
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTPS
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0  # Allow HTTPS access from anywhere
      Tags:
        - Key: AppName
          Value: CC-Midterm

  #Security group for EC2 instances to allow HTTPS and SSH
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and SSH access
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup   # Allow HTTPS access only from the loadbalancer
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/16  # Allow SSH access (restricted to internal VPC)
      Tags:
        - Key: AppName
          Value: CC-Midterm

  # Adding Rules to EC2 to RDS Security Group for EC2 Instances
  SGEgressRule1:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref EC2toRDSSecurityGroupId
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      DestinationSecurityGroupId: !Ref RDSfromEC2SecurityGroupId 

  # Launch Configuration with IAM Role and Security Group
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: MyLaunchTemplate
      LaunchTemplateData:
        ImageId: !Ref AMIId  # Choose an appropriate AMI
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !Ref EC2SecurityGroup
          - !Ref EC2toRDSSecurityGroupId
        IamInstanceProfile:
          Arn: !ImportValue  EC2InstanceProfileArn  # Use the ARN of the existing instance profile
      Tags:
        - Key: AppName
          Value: CC-Midterm

  # Target Group for Load Balancer
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VPCId
      Port: 443
      Protocol: HTTPS
      TargetType: instance
      HealthCheckProtocol: HTTPS
      HealthCheckPort: 443
      HealthCheckPath: /
      Tags:
        - Key: AppName
          Value: CC-Midterm

  # Load Balancer to distribute traffic
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - !Ref PublicSubnetId1
        - !Ref PublicSubnetId2
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Tags:
        - Key: AppName
          Value: CC-Midterm

  # Listener to route traffic to the Target Group
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-2016-08
      Certificates:
        - CertificateArn: arn:aws:acm:us-east-1:156041403412:certificate/ffc414a1-e796-44e1-b425-22ae9da4a3a0
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      Tags:
        - Key: AppName
          Value: CC-Midterm

  # Auto Scaling Group to manage EC2 instances
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PublicSubnetId1
        - !Ref PublicSubnetId2
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: 1
      MaxSize: 2
      DesiredCapacity: 1
      TargetGroupARNs:
        - !Ref TargetGroup
      Tags:
        - Key: AppName
          Value: CC-Midterm

  # CloudWatch Log Group for EC2 Instances
  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/ec2/ecommerce-application
      RetentionInDays: 7  # Optional: Retain logs for 14 days
      Tags:
        - Key: AppName
          Value: CC-Midterm

  # CloudWatch Alarm for High CPU Usage
  HighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm if CPU usage exceeds 80%"
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref AutoScalingGroup
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref ScaleUpPolicy
      Tags:
        - Key: AppName
          Value: CC-Midterm

  # CloudWatch Alarm for Low CPU Usage
  LowCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm if CPU usage drops below 20%"
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref AutoScalingGroup
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 20
      ComparisonOperator: LessThanThreshold
      AlarmActions:
        - !Ref ScaleDownPolicy
      Tags:
        - Key: AppName
          Value: CC-Midterm

  # Step Scaling Policy to Scale Up
  ScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: StepScaling
      AdjustmentType: ChangeInCapacity
      StepAdjustments:
        - MetricIntervalLowerBound: 0
          ScalingAdjustment: 1
      Cooldown: 300
      Tags:
        - Key: AppName
          Value: CC-Midterm

  # Step Scaling Policy to Scale Down
  ScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: StepScaling
      AdjustmentType: ChangeInCapacity
      StepAdjustments:
        - MetricIntervalUpperBound: 0
          ScalingAdjustment: -1
      Cooldown: 300
      Tags:
        - Key: AppName
          Value: CC-Midterm

Outputs:
  AutoScalingGroupId:
    Description: The ID of the Auto Scaling group
    Value: !Ref AutoScalingGroup

  LoadBalancerDNSName:
    Description: The DNS name of the load balancer
    Value: !GetAtt LoadBalancer.DNSName
