AWSTemplateFormatVersion: '2010-09-09'
Description: RDS Template for E-commerce Platform

Parameters:

  VPCId:
    Type: String
    Description: The VPC ID where RDS will be deployed.

  PrivateSubnetId1:
    Type: String
    Description: The private subnet ID for EC2 instances.


  PrivateSubnetId2:
    Type: String
    Description: The private subnet ID for EC2 instances.


  RDSfromEC2SecurityGroupId:
    Description: RDS to EC2 Security Group
    Type: String


  EC2toRDSSecurityGroupId:
    Description: EC2 to RDS Security Group
    Type: String

  RDSMonitoringRoleArn:
    Description: Arn for Enhanced monitoring Role
    Type: String

  DBInstanceClass:
    Description: The RDS instance type
    Type: String
    Default: db.t2.micro

Resources:
  
  SGIngressRule1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref RDSfromEC2SecurityGroupId
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId: !Ref EC2toRDSSecurityGroupId

  RDSDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !Ref PrivateSubnetId1
        - !Ref PrivateSubnetId2

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: database-1
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: 8.0.39
      DBSubnetGroupName: !Ref RDSDBSubnetGroup
      VPCSecurityGroups:
        - !Ref RDSfromEC2SecurityGroupId
      MultiAZ: true
      StorageEncrypted: true
      DBSnapshotIdentifier: mid-term-database-snapshot  # Replace with your snapshot ID
      AllocatedStorage: "20"
      StorageType: gp3
      MonitoringRoleArn: !Ref RDSMonitoringRoleArn
      MonitoringInterval: 60  # Enable detailed monitoring
      EnableCloudwatchLogsExports: ["error", "general"]
      DeletionProtection: false
      PubliclyAccessible: false
      BackupRetentionPeriod: 1

  

Outputs:
  RDSInstanceEndpoint:
    Description: The endpoint address of the RDS instance
    Value: !GetAtt RDSInstance.Endpoint.Address